// packages/ariakit-ui/src/html/badge.solid.tsx
import type { VariantProps } from "clava";
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";
import { badge, badgeLabel, badgeSlot } from "../styles/badge.ts";

export interface BadgeProps
  extends ComponentProps<"div">, VariantProps<typeof badge> {}

/**
 * @see https://ariakit.com/solid/examples/badge
 */
export function Badge(props: BadgeProps) {
  const [variantProps, rest] = splitProps(props, badge.html.propKeys);
  return <div {...badge.html(variantProps)} {...rest} />;
}

export interface BadgeLabelProps
  extends ComponentProps<"span">, VariantProps<typeof badgeLabel> {}

/**
 * @see https://ariakit.com/solid/examples/badge
 */
export function BadgeLabel(props: BadgeLabelProps) {
  const [variantProps, rest] = splitProps(props, badgeLabel.html.propKeys);
  return <span {...badgeLabel.html(variantProps)} {...rest} />;
}

export interface BadgeSlotProps
  extends ComponentProps<"span">, VariantProps<typeof badgeSlot> {}

/**
 * @see https://ariakit.com/solid/examples/badge
 */
export function BadgeSlot(props: BadgeSlotProps) {
  const [variantProps, rest] = splitProps(props, badgeSlot.html.propKeys);
  return <span {...badgeSlot.html(variantProps)} {...rest} />;
}

// packages/ariakit-ui/src/ariakit/badge.react.tsx
import * as ak from "@ariakit/react";
import type { VariantProps } from "clava";
import { splitProps } from "clava";
import { badge, badgeLabel, badgeSlot } from "../styles/badge.ts";

export interface BadgeProps
  extends ak.RoleProps<"div">, VariantProps<typeof badge> {}

/**
 * @see https://ariakit.com/react/examples/badge
 */
export function Badge(props: BadgeProps) {
  const [variantProps, rest] = splitProps(props, badge);
  return <ak.Role.div {...badge.jsx(variantProps)} {...rest} />;
}

export interface BadgeLabelProps
  extends ak.RoleProps<"span">, VariantProps<typeof badgeLabel> {}

/**
 * @see https://ariakit.com/react/examples/badge
 */
export function BadgeLabel(props: BadgeLabelProps) {
  const [variantProps, rest] = splitProps(props, badgeLabel);
  return <ak.Role.span {...badgeLabel.jsx(variantProps)} {...rest} />;
}

export interface BadgeSlotProps
  extends ak.RoleProps<"span">, VariantProps<typeof badgeSlot> {}

/**
 * @see https://ariakit.com/react/examples/badge
 */
export function BadgeSlot(props: BadgeSlotProps) {
  const [variantProps, rest] = splitProps(props, badgeSlot);
  return <ak.Role.span {...badgeSlot.jsx(variantProps)} {...rest} />;
}
