// packages/ariakit-ui/src/html/link.solid.tsx
import type { VariantProps } from "clava";
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";
import { link } from "../styles/link.ts";

export interface LinkProps
  extends ComponentProps<"a">, VariantProps<typeof link> {}

export function Link(props: LinkProps) {
  const [variantProps, rest] = splitProps(props, link.html.propKeys);
  return <a {...link.html(variantProps)} {...rest} />;
}

// packages/ariakit-ui/src/ariakit/link.react.tsx
import * as ak from "@ariakit/react";
import type { VariantProps } from "clava";
import { splitProps } from "clava";
import { link } from "../styles/link.ts";

export interface LinkProps
  extends ak.RoleProps<"a">, VariantProps<typeof link> {}

/**
 * Renders an inline text link as an anchor element. Use the `render` prop to
 * swap in a framework router link.
 */
export function Link(props: LinkProps) {
  const [variantProps, rest] = splitProps(props, link);
  return <ak.Role.a {...link.jsx(variantProps)} {...rest} />;
}
