// packages/ariakit-ui/src/html/table.solid.tsx
import type { VariantProps } from "clava";
import type { Accessor, ComponentProps } from "solid-js";
import { createContext, splitProps, useContext } from "solid-js";
import { Dynamic } from "solid-js/web";
import {
  table,
  tableCell,
  tableContainer,
  tableFoot,
  tableHead,
  tableRow,
  tableRowGroup,
  tableScroller,
} from "../styles/table.ts";

type TableRowGroupKind = "head" | "body" | "foot";

// Lets rows and cells pick up the enclosing row group's kind without
// repeating the group prop on every descendant. The context carries an
// accessor because Solid providers read their value untracked, so a plain
// value would freeze descendants at the mount-time group.
const defaultTableRowGroup: Accessor<TableRowGroupKind> = () => "body";
const TableRowGroupContext = createContext(defaultTableRowGroup);

export interface TableContainerProps
  extends ComponentProps<"div">, VariantProps<typeof tableContainer> {}

/**
 * Renders the framed wrapper that rounds the table's corners and draws its
 * outer borders. Place a `TableScroller` with the `Table` inside.
 */
export function TableContainer(props: TableContainerProps) {
  const [variantProps, rest] = splitProps(props, tableContainer.html.propKeys);
  return <div {...tableContainer.html(variantProps)} {...rest} />;
}

export interface TableScrollerProps
  extends ComponentProps<"div">, VariantProps<typeof tableScroller> {}

/**
 * Renders the scroll area that lets the table rows scroll under sticky row
 * groups. Must be placed inside a `TableContainer`, wrapping the `Table`.
 */
export function TableScroller(props: TableScrollerProps) {
  const [variantProps, rest] = splitProps(props, tableScroller.html.propKeys);
  return <div {...tableScroller.html(variantProps)} {...rest} />;
}

export interface TableProps
  extends ComponentProps<"table">, VariantProps<typeof table> {}

/**
 * Renders a styled `<table>` element. Compose
 * `TableContainer > TableScroller > Table` for the framed look with rounded
 * corners and outer borders.
 */
export function Table(props: TableProps) {
  const [variantProps, rest] = splitProps(props, table.html.propKeys);
  return <table {...table.html(variantProps)} {...rest} />;
}

export interface TableRowGroupProps
  extends
    ComponentProps<"tbody" | "thead" | "tfoot">,
    VariantProps<typeof tableRowGroup> {
  /** The group of rows to render. */
  group?: TableRowGroupKind;
}

/**
 * Renders `<thead>`, `<tbody>`, or `<tfoot>` based on the `group` prop and
 * provides the group to the `TableRow` and `TableCell` components inside.
 * Must be placed inside a `Table`.
 */
export function TableRowGroup(props: TableRowGroupProps) {
  // The head and foot styles extend the base row group style without adding
  // variants, so the base prop keys split all of them.
  const [localProps, variantProps, rest] = splitProps(
    props,
    ["group"],
    tableRowGroup.html.propKeys,
  );
  const group = () => localProps.group ?? "body";
  const groupStyle = () =>
    group() === "head"
      ? tableHead
      : group() === "foot"
        ? tableFoot
        : tableRowGroup;
  return (
    <TableRowGroupContext.Provider value={group}>
      <Dynamic
        component={
          group() === "head" ? "thead" : group() === "foot" ? "tfoot" : "tbody"
        }
        {...groupStyle().html(variantProps)}
        {...rest}
      />
    </TableRowGroupContext.Provider>
  );
}

export interface TableRowProps
  extends ComponentProps<"tr">, VariantProps<typeof tableRow> {
  /** The group of rows to render. */
  group?: TableRowGroupKind;
}

/**
 * Renders a `<tr>` element. Must be placed inside a `TableRowGroup`, whose
 * group the row inherits so only body rows get the hover tint.
 */
export function TableRow(props: TableRowProps) {
  const context = useContext(TableRowGroupContext);
  const [localProps, variantProps, rest] = splitProps(
    props,
    ["group"],
    tableRow.html.propKeys,
  );
  const group = () => localProps.group ?? context();
  return (
    <tr
      {...tableRow.html({
        ...variantProps,
        $hover: variantProps.$hover ?? group() === "body",
      })}
      {...rest}
    />
  );
}

// The `$header` and `$numeric` variants are computed from the `header` and
// `numeric` props, so they're omitted from the public props and must not be
// part of the split keys.
const tableCellPropKeys = tableCell.html.propKeys.filter(
  (key) => key !== "$header" && key !== "$numeric",
);

export interface TableCellProps
  extends
    ComponentProps<"td">,
    // The semantic props below compute these variants along with the
    // element and its scope, so they stay in sync.
    Omit<VariantProps<typeof tableCell>, "$header" | "$numeric"> {
  /** Whether the cell is numeric. */
  numeric?: boolean;
  /** Whether the cell is a header. */
  header?: "column" | "row" | boolean;
}

/**
 * Renders a `<th>` or `<td>` element with the matching `scope` attribute
 * based on the `header` prop. Must be placed inside a `TableRow`; cells in a
 * head `TableRowGroup` default to column headers.
 */
export function TableCell(props: TableCellProps) {
  const group = useContext(TableRowGroupContext);
  const [localProps, variantProps, rest] = splitProps(
    props,
    ["numeric", "header"],
    tableCellPropKeys,
  );
  const header = () =>
    localProps.header ?? (group() === "head" ? "column" : false);
  // Only the bare `true` value derives the header kind from the group, so an
  // explicit "row" stays a row header even inside a head group.
  const isColumnHeader = () =>
    header() === "column" || (header() === true && group() === "head");
  const isRowHeader = () =>
    header() === "row" || (header() === true && group() !== "head");

  const getScope = () => {
    if (!header()) return;
    if (isColumnHeader()) return "col";
    if (isRowHeader()) return "row";
    return;
  };

  return (
    <Dynamic
      component={header() ? "th" : "td"}
      scope={getScope()}
      {...tableCell.html({
        $header: isColumnHeader() ? "column" : isRowHeader() ? "row" : false,
        $numeric: !!localProps.numeric,
        ...variantProps,
      })}
      {...rest}
    />
  );
}

// packages/ariakit-ui/src/ariakit/table.react.tsx
import * as ak from "@ariakit/react";
import type { VariantProps } from "clava";
import { splitProps } from "clava";
import * as React from "react";
import { createRender } from "../react-utils/create-render.ts";
import { isIterable } from "../react-utils/is-iterable.ts";
import {
  table,
  tableCell,
  tableContainer,
  tableFoot,
  tableHead,
  tableRow,
  tableRowGroup,
  tableScroller,
} from "../styles/table.ts";

type TableRowGroupKind = "head" | "body" | "foot";

export type TableRow<K extends keyof any> = {
  group?: TableRowGroupKind;
} & Record<K, React.ReactNode | TableCellProps>;

export type TableRows<K extends keyof any> = TableRow<K>[];

const TableRowGroupContext = React.createContext<TableRowGroupKind>("body");

export interface TableProps<K extends keyof any>
  extends React.ComponentProps<"table">, VariantProps<typeof table> {
  /** Custom container element or props to render a `TableContainer`. */
  container?: React.ReactElement | TableContainerProps;
  /** Custom scroller element or props to render a `TableScroller`. */
  scroller?: React.ReactElement | TableScrollerProps;
  /** Custom head row group element or props to render a `TableRowGroup`. */
  head?: React.ReactElement | TableRowGroupProps;
  /** Custom body row group element or props to render a `TableRowGroup`. */
  body?: React.ReactElement | TableRowGroupProps;
  /** Custom foot row group element or props to render a `TableRowGroup`. */
  foot?: React.ReactElement | TableRowGroupProps;
  /** Custom row element or props to render a `TableRow` for body rows. */
  row?: React.ReactElement | TableRowProps;
  /** Custom row element or props to render a `TableRow` for head rows. */
  headRow?: React.ReactElement | TableRowProps;
  /** Custom row element or props to render a `TableRow` for foot rows. */
  footRow?: React.ReactElement | TableRowProps;
  /**
   * Declarative rows data. Keys map to columns; values are cell content or
   * props.
   */
  rows?: TableRows<K>;
}

/**
 * Composable table with optional container/scroller and declarative rows.
 * @example
 * <Table>
 *   <TableRowGroup group="head">
 *     <TableRow>
 *       <TableCell header>Name</TableCell>
 *       <TableCell header numeric>Age</TableCell>
 *     </TableRow>
 *   </TableRowGroup>
 *   <TableRowGroup>
 *     <TableRow>
 *       <TableCell>Ada</TableCell>
 *       <TableCell numeric>37</TableCell>
 *     </TableRow>
 *   </TableRowGroup>
 * </Table>
 * @example
 * <Table
 *   rows={[
 *     { group: "head", name: "Name", age: { children: "Age", numeric: true } },
 *     { name: "Ada", age: 37 },
 *   ]}
 * />
 */
export function Table<K extends keyof any>({
  children,
  container,
  scroller,
  head,
  body,
  foot,
  row,
  headRow = row,
  footRow = row,
  rows,
  ...props
}: TableProps<K>) {
  const [variantProps, rest] = splitProps(props, table);
  const containerEl = createRender(TableContainer, container);
  const scrollerEl = createRender(TableScroller, scroller);
  const headEl = createRender(TableRowGroup, head, { group: "head" });
  const bodyEl = createRender(TableRowGroup, body);
  const footEl = createRender(TableRowGroup, foot, { group: "foot" });
  const rowEl = createRender(TableRow, row);
  const headRowEl = createRender(TableRow, headRow, { group: "head" });
  const footRowEl = createRender(TableRow, footRow, { group: "foot" });
  const headRows = rows?.filter((row) => row.group === "head");
  const bodyRows = rows?.filter((row) => row.group === "body" || !row.group);
  const footRows = rows?.filter((row) => row.group === "foot");

  const getRowElement = (row: TableRow<K>) => {
    if (row.group === "head") return headRowEl;
    if (row.group === "foot") return footRowEl;
    return rowEl;
  };

  const isNumericColumn = (row: TableRow<K>, key: K) => {
    const cell = row[key];
    if (!cell) return false;
    if (typeof cell !== "object") return false;
    if (React.isValidElement<TableCellProps>(cell)) {
      return Boolean(cell.props.numeric);
    }
    if (isIterable(cell)) return false;
    if (React.isValidElement<any>(cell)) return false;
    if (!Object.hasOwn(cell, "numeric")) return false;
    return Boolean((cell as TableCellProps).numeric);
  };

  const renderRow = (row: TableRow<K>, index: number) => {
    const rowElement = getRowElement(row);
    return (
      <ak.Role key={index} render={rowElement}>
        {Object.entries(row).map(([key, value]) => {
          if (key === "group") return null;
          if (value == null) return null;
          const tableCellElement = createRender(TableCell, value, {
            numeric: !!headRows?.some((row) => isNumericColumn(row, key as K)),
            header: row.group === "head" ? "column" : false,
            children: key,
          } as const);
          return <ak.Role key={key} render={tableCellElement} />;
        })}
      </ak.Role>
    );
  };

  return (
    <ak.Role render={containerEl}>
      <ak.Role render={scrollerEl}>
        <table {...table.jsx(variantProps)} {...rest}>
          {rows?.length ? (
            <>
              {!!headRows?.length && (
                <ak.Role render={headEl}>
                  {headRows.map((row, index) => renderRow(row, index))}
                </ak.Role>
              )}
              {!!(bodyRows?.length || children) && (
                <ak.Role render={bodyEl}>
                  {bodyRows?.map((row, index) => renderRow(row, index))}
                  {children}
                </ak.Role>
              )}
              {!!footRows?.length && (
                <ak.Role render={footEl}>
                  {footRows.map((row, index) => renderRow(row, index))}
                </ak.Role>
              )}
            </>
          ) : (
            children
          )}
        </table>
      </ak.Role>
    </ak.Role>
  );
}

export interface TableContainerProps
  extends React.ComponentProps<"div">, VariantProps<typeof tableContainer> {}

export function TableContainer(props: TableContainerProps) {
  const [variantProps, rest] = splitProps(props, tableContainer);
  return <div {...tableContainer.jsx(variantProps)} {...rest} />;
}

export interface TableScrollerProps
  extends React.ComponentProps<"div">, VariantProps<typeof tableScroller> {}

export function TableScroller(props: TableScrollerProps) {
  const [variantProps, rest] = splitProps(props, tableScroller);
  return <div {...tableScroller.jsx(variantProps)} {...rest} />;
}

export interface TableRowGroupProps
  extends
    React.ComponentProps<"tbody" | "thead" | "tfoot">,
    VariantProps<typeof tableRowGroup> {
  /** The group of rows to render. */
  group?: TableRowGroupKind;
}

export function TableRowGroup({
  group = "body",
  ...props
}: TableRowGroupProps) {
  const Component =
    group === "head" ? "thead" : group === "foot" ? "tfoot" : "tbody";
  const groupStyle =
    group === "head" ? tableHead : group === "foot" ? tableFoot : tableRowGroup;
  const [variantProps, rest] = splitProps(props, groupStyle);
  return (
    <TableRowGroupContext.Provider value={group}>
      <Component {...groupStyle.jsx(variantProps)} {...rest} />
    </TableRowGroupContext.Provider>
  );
}

export interface TableRowProps
  extends React.ComponentProps<"tr">, VariantProps<typeof tableRow> {
  /** The group of rows to render. */
  group?: TableRowGroupKind;
}

export function TableRow({ group, ...props }: TableRowProps) {
  const contextGroup = React.useContext(TableRowGroupContext);
  group = group ?? contextGroup;
  const [variantProps, rest] = splitProps(props, tableRow);
  return (
    <tr
      {...tableRow.jsx({ $hover: group === "body", ...variantProps })}
      {...rest}
    />
  );
}

export interface TableCellProps
  extends
    React.ComponentProps<"td">,
    // The semantic props below compute these variants along with the
    // element and its scope, so they stay in sync.
    Omit<VariantProps<typeof tableCell>, "$header" | "$numeric"> {
  /** Whether the cell is numeric. */
  numeric?: boolean;
  /** Whether the cell is a header. */
  header?: "column" | "row" | boolean;
}

export function TableCell({ numeric, header, ...props }: TableCellProps) {
  const group = React.useContext(TableRowGroupContext);
  header = header ?? (group === "head" ? "column" : false);
  // Only the bare `true` value derives the header kind from the group, so an
  // explicit "row" stays a row header even inside a head group.
  const isColumnHeader =
    header === "column" || (header === true && group === "head");
  const isRowHeader = header === "row" || (header === true && group !== "head");
  const Component = header ? "th" : "td";
  const [variantProps, rest] = splitProps(props, tableCell);

  const getScope = () => {
    if (!header) return;
    if (isColumnHeader) return "col";
    if (isRowHeader) return "row";
    return;
  };

  return (
    <Component
      scope={getScope()}
      {...tableCell.jsx({
        $header: isColumnHeader ? "column" : isRowHeader ? "row" : false,
        $numeric: !!numeric,
        ...variantProps,
      })}
      {...rest}
    />
  );
}
