// packages/ariakit-solid-utils/src/system.tsx
/**
 * Helpers for creating and composing Ariakit Solid components.
 * @module System utilities
 */

import type { Store } from "@ariakit/store";
import type { AnyObject, EmptyObject } from "@ariakit/utils";
import type {
  Accessor,
  Component,
  ComponentProps,
  JSX,
  ValidComponent,
} from "solid-js";
import {
  createMemo,
  mergeProps,
  splitProps,
  createContext as solidCreateContext,
  useContext as solidUseContext,
} from "solid-js";
import { Dynamic } from "solid-js/web";
import type {
  ExtractPropsWithDefaultsExtractedProps,
  ExtractPropsWithDefaultsRestProps,
} from "./reactivity.ts";
import { extractPropsWithDefaults } from "./reactivity.ts";
import type {
  Hook,
  HTMLProps,
  Options,
  Props,
  WrapInstance,
  WrapInstanceValue,
} from "./types.ts";

/**
 * Creates a Solid component instance that supports the `render` and
 * `wrapInstance` props.
 */
export function createInstance(
  Component: ValidComponent,
  props: Props<ValidComponent, Options>,
) {
  // TODO: consider adding a dev-only runtime check to clarify that
  // the JSX.Element type is only accepted through `As`, so that
  // the error is not a vague "value is not a function" error.
  const [features, rest] = splitProps(
    props as typeof props & { _metadataProps?: unknown },
    ["render", "wrapInstance", "_metadataProps"],
  );
  // Internal metadata props (see `createMetadataProps`) must reach a composed
  // component so they keep propagating down the tree, but must not be spread
  // onto a host element, where they would leak as a DOM attribute.
  const withRender = () => (
    // TODO: replace with LazyDynamic
    <Dynamic
      {...mergeProps(rest, {
        get _metadataProps() {
          const component = (features.render as ValidComponent) ?? Component;
          return typeof component === "function"
            ? features._metadataProps
            : undefined;
        },
      })}
      component={(features.render as ValidComponent) ?? Component}
    />
  );
  let tree = withRender;
  if (features.wrapInstance) {
    for (const element of features.wrapInstance) {
      const children = tree;
      tree = () => (
        // TODO: replace with LazyDynamic
        <Dynamic component={element as ValidComponent}>{children()}</Dynamic>
      );
    }
  }
  return tree();
}

/**
 * Returns props with an additional `wrapInstance` prop.
 */
export function wrapInstance<
  P,
  // oxlint-disable-next-line no-unnecessary-type-parameters
  Q = P & { wrapInstance: WrapInstance },
>(props: P & { wrapInstance?: WrapInstance }, element: WrapInstanceValue): Q {
  const wrapInstance = [...(props.wrapInstance ?? []), element];
  return mergeProps(props, { wrapInstance }) as Q;
}

/**
 * Creates a component hook that accepts props and returns props so they can be
 * passed to a Solid component.
 */
export function createHook<
  T extends ValidComponent,
  P extends AnyObject = EmptyObject,
>(useProps: (props: Props<T, P>) => HTMLProps<T, P>) {
  return useProps as Hook<T, P>;
}

/**
 * Splits "option props" from the rest in a component hook. Must be called
 * inside `createHook`.
 *
 * The first argument is an object that defines the props that will be extracted,
 * with their default values. To extract a prop without a default, set it to
 * `undefined`.
 *
 * The hook function must be passed as the second argument, and it will receive
 * the rest of the props and the extracted options.
 * @example
 * ```jsx
 * export const useMyComponent = createHook<TagName, MyComponentOptions>(
 *   withOptions(
 *     { orientation: "horizontal" },
 *     function useMyComponent(props, options) {
 *       // ...
 *     },
 *   ),
 * );
 * ```
 */
export function withOptions<
  T extends ValidComponent,
  P extends AnyObject,
  const D extends Partial<ComputedP>,
  ComputedP extends Props<T, P>,
>(
  defaults: D,
  useProps: (
    props: ExtractPropsWithDefaultsRestProps<ComputedP, D>,
    options: ExtractPropsWithDefaultsExtractedProps<ComputedP, D>,
  ) => HTMLProps<T, P>,
): (props: ComputedP) => HTMLProps<T, P> {
  return function usePropsWithOptions(props: ComputedP) {
    const [options, rest] = extractPropsWithDefaults(props, defaults);
    return useProps(rest, options);
  };
}

/**
 * Passes metadata props around the component tree without leaking them to the
 * DOM. The metadata is carried on the internal `_metadataProps` prop, which
 * `createInstance` strips before rendering a host element. A plain (non-`on*`)
 * prop is used on purpose: `mergeProps`/`combineProps` would chain an `on*`
 * carrier into a wrapper function and drop the attached symbols during
 * composition, whereas a plain prop survives the merge with its symbols intact.
 * Returns a reactive accessor for the parent value and the props that forward
 * the augmented metadata to descendants.
 * @example
 * ```jsx
 * const symbol = Symbol("command");
 * function useCommand(props) {
 *   const [isDuplicate, metadataProps] = createMetadataProps(props, symbol, () => true);
 *   props = mergeProps(props, metadataProps);
 *   // isDuplicate() is true when a parent already set the symbol.
 * }
 * ```
 */
export function createMetadataProps<T, K extends keyof any>(
  props: { _metadataProps?: { [key in K]?: T } },
  key: K,
  value: () => T,
) {
  const parent = () => props._metadataProps as { [P in K]?: T } | undefined;
  const carrier = createMemo(() =>
    Object.assign(
      {},
      parent(),
      value() !== undefined ? { [key]: value() } : undefined,
    ),
  );
  return [
    () => parent()?.[key],
    {
      get _metadataProps() {
        return carrier();
      },
    },
  ] as const;
}

type StoreProvider<T extends Store> = Component<{
  value: Accessor<T | undefined>;
  children?: JSX.Element;
}>;

type RenderFn = () => JSX.Element;

/**
 * Creates an Ariakit store context with hooks and provider components. Unlike
 * the React equivalent, the context value is an `Accessor<T>` rather than the
 * store object itself, because Ariakit Solid stores are accessors.
 */
export function createStoreContext<T extends Store>(
  providers: StoreProvider<T>[] = [],
  scopedProviders: StoreProvider<T>[] = [],
) {
  const context = solidCreateContext<Accessor<T | undefined>>(() => undefined);
  const scopedContext = solidCreateContext<Accessor<T | undefined>>(
    () => undefined,
  );

  const useContext = () => solidUseContext(context);

  const useScopedContext = (onlyScoped = false) => {
    const scoped = solidUseContext(scopedContext);
    const store = useContext();
    if (onlyScoped) return scoped;
    return () => scoped() || store();
  };

  const useProviderContext = () => {
    const scoped = solidUseContext(scopedContext);
    const store = useContext();
    return () => {
      const $scoped = scoped();
      const $store = store();
      if ($scoped && $scoped === $store) return;
      return $store;
    };
  };

  const ContextProvider = (props: ComponentProps<typeof context.Provider>) => {
    return providers.reduceRight<RenderFn>(
      (children, Provider) => () => (
        <Provider {...props}>{children()}</Provider>
      ),
      () => <context.Provider {...props} />,
    )();
  };

  const ScopedContextProvider = (
    props: ComponentProps<typeof scopedContext.Provider>,
  ) => {
    return (
      <ContextProvider {...props}>
        {scopedProviders.reduceRight<RenderFn>(
          (children, Provider) => () => (
            <Provider {...props}>{children()}</Provider>
          ),
          () => <scopedContext.Provider {...props} />,
        )()}
      </ContextProvider>
    );
  };

  return {
    context,
    scopedContext,
    useContext,
    useScopedContext,
    useProviderContext,
    ContextProvider,
    ScopedContextProvider,
  };
}

// packages/ariakit-react-utils/src/system.tsx
/**
 * Helpers for creating and composing Ariakit React components.
 * @module System utilities
 */

import type { Store } from "@ariakit/store";
import type { AnyFunction, AnyObject, EmptyObject } from "@ariakit/utils";
import * as React from "react";
import { useMergeRefs } from "./hooks.ts";
import { getRefProperty, mergeProps } from "./misc.ts";
import type { Hook, HTMLProps, Options, Props } from "./types.ts";

/**
 * The same as `React.forwardRef` but passes the `ref` as a prop and returns a
 * component with the same generic type.
 */
export function forwardRef<T extends React.FC<any>>(render: T) {
  const Role = React.forwardRef(
    // @ts-ignore Incompatible with React 19 types. Ignore for now.
    (props, ref) => render({ ...props, ref }),
  );
  Role.displayName = render.displayName || render.name;
  return Role as unknown as T;
}

/**
 * The same as `React.memo` but returns a component with the same generic type.
 */
export function memo<T extends React.FC<any>>(
  Component: T,
  propsAreEqual?: (
    prevProps: Readonly<React.ComponentPropsWithoutRef<T>>,
    nextProps: Readonly<React.ComponentPropsWithoutRef<T>>,
  ) => boolean,
) {
  return React.memo(Component, propsAreEqual) as unknown as T;
}

/**
 * Creates a React element that supports the `render` and `wrapElement` props.
 */
export function createElement(
  Type: React.ElementType,
  props: Props<React.ElementType, Options>,
) {
  const { wrapElement, render, ...rest } = props;
  const mergedRef = useMergeRefs(props.ref, getRefProperty(render));

  let element: React.ReactElement;

  if (React.isValidElement<any>(render)) {
    const renderProps = {
      // @ts-ignore Incompatible with React 19 types. Ignore for now.
      ...render.props,
      ref: mergedRef,
    };
    element = React.cloneElement(render, mergeProps(rest, renderProps));
  } else if (render) {
    element = render(rest) as React.ReactElement;
  } else {
    element = <Type {...rest} />;
  }

  if (wrapElement) {
    return wrapElement(element);
  }

  return element;
}

/**
 * Creates a component hook that accepts props and returns props so they can be
 * passed to a React element.
 */
export function createHook<
  T extends React.ElementType,
  P extends AnyObject = EmptyObject,
>(useProps: (props: Props<T, P>) => HTMLProps<T, P>) {
  const useRole = (props: Props<T, P> = {} as Props<T, P>) => {
    return useProps(props);
  };
  useRole.displayName = useProps.name;
  return useRole as Hook<T, P>;
}

type StoreProvider<T extends Store> = React.ComponentType<{
  value: T | undefined;
  children?: React.ReactNode;
}>;

/**
 * Key used to brand provider components created by `createStoreContext` so
 * store props and `useStoreState` can resolve them to their store context.
 * `Symbol.for` is used so different copies of this module still recognize each
 * other's provider components.
 */
export const providerComponentSymbol: unique symbol = Symbol.for(
  "ariakit.provider-component",
);

interface ProviderComponentBrand<T extends Store = Store> {
  /**
   * Phantom property that carries the provider's store type. It makes provider
   * components assignable to `ProviderComponent` types of base stores (for
   * example, `ComboboxProvider` to `ProviderComponent<CompositeStore>`), which
   * wouldn't be possible if the store type only appeared in the invariant
   * `React.Context` position. Never set at runtime.
   */
  store?: T;
}

interface ProviderComponentValue<
  T extends Store = Store,
> extends ProviderComponentBrand<T> {
  context: React.Context<T | undefined>;
}

/**
 * A provider component (for example, `ComboboxProvider`) that can be passed to
 * store props and [`useStoreState`](https://ariakit.com/reference/use-store-state)
 * in place of a store object. The store is then read from the closest matching
 * provider via context.
 */
export interface ProviderComponent<T extends Store = Store> {
  readonly [providerComponentSymbol]: ProviderComponentBrand<T>;
}

/**
 * Checks whether the value is a provider component created by
 * `createStoreContext` (for example, `ComboboxProvider`).
 */
export function isProviderComponent<T extends Store>(
  value: T | ProviderComponent<T> | null | undefined,
): value is ProviderComponent<T>;

export function isProviderComponent(value: unknown): value is ProviderComponent;

export function isProviderComponent(
  value: unknown,
): value is ProviderComponent {
  if (typeof value !== "function") return false;
  return providerComponentSymbol in value;
}

function getProviderComponentContext<T extends Store>(
  provider: ProviderComponent<T>,
) {
  // The brand slot is always created by createStoreContext with the context
  // attached, so it can be safely narrowed to its full runtime shape.
  const value = provider[providerComponentSymbol] as ProviderComponentValue<T>;
  return value.context;
}

const emptyStoreContext = React.createContext<Store | undefined>(undefined);

/**
 * Resolves the value of a `store` prop that may receive either a store object
 * or a provider component. When a provider component is passed, it's an
 * explicit reference to that specific provider: the store is read only from
 * the closest matching provider's context, without falling back to the given
 * fallback stores, so it may be `undefined` if no matching provider is found.
 * Otherwise, the store prop itself is returned, falling back to the given
 * fallback stores (typically the component's own context) when it's not
 * provided.
 *
 * The store type is inferred only from the `store` prop; the fallback stores
 * are loosely typed so they never widen or poison that inference.
 */
export function useStoreProp<T extends Store>(
  store: T | ProviderComponent<T> | null | undefined,
  ...fallbacks: Array<Store | null | undefined>
): T | undefined;

export function useStoreProp(
  store: Store | ProviderComponent | null | undefined,
  ...fallbacks: Array<Store | null | undefined>
): Store | undefined {
  const isProvider = isProviderComponent(store);
  // Hooks must be called unconditionally, so always read a context: the
  // provider component's own context when the store is a provider component, or
  // an always empty context otherwise (its value is always undefined).
  const providerContext = isProvider
    ? getProviderComponentContext(store)
    : emptyStoreContext;
  const contextStore = React.useContext(providerContext);
  if (isProvider) return contextStore;
  if (store) return store;
  for (const fallback of fallbacks) {
    if (fallback) return fallback;
  }
  return;
}

/**
 * Creates an Ariakit store context with hooks and provider components.
 */
export function createStoreContext<T extends Store>(
  providers: StoreProvider<T>[] = [],
  scopedProviders: StoreProvider<T>[] = [],
) {
  const context = React.createContext<T | undefined>(undefined);
  const scopedContext = React.createContext<T | undefined>(undefined);

  const useContext = () => React.useContext(context);

  const useScopedContext = (onlyScoped = false) => {
    const scoped = React.useContext(scopedContext);
    const store = useContext();
    if (onlyScoped) return scoped;
    return scoped || store;
  };

  const useProviderContext = () => {
    const scoped = React.useContext(scopedContext);
    const store = useContext();
    if (scoped && scoped === store) return;
    return store;
  };

  const ContextProvider = (
    props: React.ComponentPropsWithoutRef<typeof context.Provider>,
  ) => {
    return providers.reduceRight(
      (children, Provider) => <Provider {...props}>{children}</Provider>,
      <context.Provider {...props} />,
    );
  };

  const ScopedContextProvider = (
    props: React.ComponentPropsWithoutRef<typeof scopedContext.Provider>,
  ) => {
    return (
      <ContextProvider {...props}>
        {scopedProviders.reduceRight(
          (children, Provider) => (
            <Provider {...props}>{children}</Provider>
          ),
          <scopedContext.Provider {...props} />,
        )}
      </ContextProvider>
    );
  };

  const createProviderComponent = <C extends AnyFunction>(
    component: C,
  ): C & ProviderComponent<T> => {
    const value: ProviderComponentValue<T> = { context };
    return Object.assign(component, { [providerComponentSymbol]: value });
  };

  return {
    context,
    scopedContext,
    useContext,
    useScopedContext,
    useProviderContext,
    ContextProvider,
    ScopedContextProvider,
    createProviderComponent,
  };
}
