// packages/ariakit-ui/src/html/checkbox-card.react.tsx
import type { VariantProps } from "clava";
import { splitProps } from "clava";
import type { ComponentProps } from "react";
import { badge, badgeIcon, badgeText } from "../styles/badge.ts";

export interface BadgeProps
  extends ComponentProps<"div">,
    VariantProps<typeof badge>,
    VariantProps<typeof badgeText> {
  iconStart?: React.ReactNode;
  iconEnd?: React.ReactNode;
}

export function Badge({ iconStart, iconEnd, ...props }: BadgeProps) {
  const [variantProps, textProps, rest] = splitProps(props, badge, badgeText);
  return (
    <div {...badge(variantProps)} {...rest}>
      {iconStart && (
        <span {...badgeIcon({ $position: "start" })}>{iconStart}</span>
      )}
      <span {...badgeText(textProps)}>{props.children}</span>
      {iconEnd && <span {...badgeIcon({ $position: "end" })}>{iconEnd}</span>}
    </div>
  );
}

// packages/ariakit-ui/src/html/checkbox-card.solid.tsx
import type { VariantProps } from "clava";
import type { ComponentProps, JSXElement } from "solid-js";
import { Show, splitProps } from "solid-js";
import { badge, badgeIcon, badgeText } from "../styles/badge.ts";

export interface BadgeProps
  extends ComponentProps<"div">,
    VariantProps<typeof badge>,
    VariantProps<typeof badgeText> {
  iconStart?: JSXElement;
  iconEnd?: JSXElement;
}

export function Badge(props: BadgeProps) {
  const [variantProps, textProps, iconProps, rest] = splitProps(
    props,
    badge.html.propKeys,
    badgeText.variantKeys,
    ["iconStart", "iconEnd"],
  );
  return (
    <div {...badge.html(variantProps)} {...rest}>
      <Show when={iconProps.iconStart}>
        <span {...badgeIcon.html({ $position: "start" })}>
          {iconProps.iconStart}
        </span>
      </Show>
      <span {...badgeText.html(textProps)}>{props.children}</span>
      <Show when={iconProps.iconEnd}>
        <span {...badgeIcon.html({ $position: "end" })}>
          {iconProps.iconEnd}
        </span>
      </Show>
    </div>
  );
}
