// packages/ariakit-ui/src/html/command.react.tsx
import type { ComponentProps } from "react";
import { command } from "../styles/command.ts";
import type { VariantProps } from "../utils/cv.ts";

export interface CommandProps
  extends VariantProps<typeof command>,
    ComponentProps<"button"> {}

export function Command(props: CommandProps) {
  const [variantProps, rest] = command.splitProps(props);
  return <button {...rest} className={command(variantProps)} />;
}

// packages/ariakit-ui/src/html/command.solid.tsx
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";
import { command } from "../styles/command.ts";
import type { VariantProps } from "../utils/cv.ts";

export interface CommandProps
  extends VariantProps<typeof command>,
    ComponentProps<"button"> {}

export function Command(props: CommandProps) {
  const [variantProps, rest] = splitProps(props, command.variantProps);
  return <button {...rest} class={command(variantProps)} />;
}
