// packages/ariakit-ui/src/html/input.solid.tsx
import type { VariantProps } from "clava";
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";
import { input } from "../styles/input.ts";

export interface InputProps
  extends ComponentProps<"input">, VariantProps<typeof input> {}

export function Input(props: InputProps) {
  const [variantProps, rest] = splitProps(props, input.html.propKeys);
  return <input {...input.html(variantProps)} {...rest} />;
}

// packages/ariakit-ui/src/html/input.react.tsx
import type { VariantProps } from "clava";
import { splitProps } from "clava";
import type { ComponentProps } from "react";
import { input } from "../styles/input.ts";

export interface InputProps
  extends ComponentProps<"input">, VariantProps<typeof input> {}

export function Input(props: InputProps) {
  const [variantProps, rest] = splitProps(props, input);
  return <input {...input.jsx(variantProps)} {...rest} />;
}
