// packages/ariakit-ui/src/html/link.solid.tsx
import type { VariantProps } from "clava";
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";
import { link } from "../styles/link.ts";

export interface LinkProps
  extends ComponentProps<"a">, VariantProps<typeof link> {}

export function Link(props: LinkProps) {
  const [variantProps, rest] = splitProps(props, link.html.propKeys);
  return <a {...link.html(variantProps)} {...rest} />;
}

// packages/ariakit-ui/src/html/link.react.tsx
import type { VariantProps } from "clava";
import { splitProps } from "clava";
import type { ComponentProps } from "react";
import { link } from "../styles/link.ts";

export interface LinkProps
  extends ComponentProps<"a">, VariantProps<typeof link> {}

export function Link(props: LinkProps) {
  const [variantProps, rest] = splitProps(props, link);
  return <a {...link.jsx(variantProps)} {...rest} />;
}
