// packages/ariakit-ui/src/html/prose.solid.tsx
import type { VariantProps } from "clava";
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";
import { prose } from "../styles/prose.ts";

export interface ProseProps
  extends ComponentProps<"div">, VariantProps<typeof prose> {}

export function Prose(props: ProseProps) {
  const [variantProps, rest] = splitProps(props, prose.html.propKeys);
  return <div {...prose.html(variantProps)} {...rest} />;
}

// packages/ariakit-ui/src/html/prose.react.tsx
import type { VariantProps } from "clava";
import { splitProps } from "clava";
import type { ComponentProps } from "react";
import { prose } from "../styles/prose.ts";

export interface ProseProps
  extends ComponentProps<"div">, VariantProps<typeof prose> {}

export function Prose(props: ProseProps) {
  const [variantProps, rest] = splitProps(props, prose);
  return <div {...prose.jsx(variantProps)} {...rest} />;
}
