// packages/ariakit-solid-components/src/heading/heading.tsx
import {
  extractTagName,
  createRef,
  mergeProps,
  createHook,
  createInstance,
} from "@ariakit/solid-utils";
import type { Options, Props } from "@ariakit/solid-utils";
import type { ValidComponent } from "solid-js";
import { createMemo, useContext } from "solid-js";
import { HeadingContext } from "./heading-context.tsx";
import type { HeadingLevels } from "./utils.ts";

type HeadingElements = `h${HeadingLevels}`;
const TagName = "h1" satisfies ValidComponent;
type TagName = HeadingElements;
type HTMLType = HTMLElementTagNameMap[TagName];

/**
 * Returns props to create a `Heading` component. The element type (or the
 * `aria-level` prop, if the element type is not a native heading) is determined
 * by the context level provided by the parent `HeadingLevel` component.
 * @see https://solid.ariakit.com/components/heading
 * @example
 * ```jsx
 * const props = useHeading();
 * <Role {...props}>Heading</Role>
 * ```
 */
export const useHeading = createHook<TagName, HeadingOptions>(
  function useHeading(props) {
    const ref = createRef<HTMLType>();
    const level = useContext(HeadingContext) || (() => 1);
    const Element = () => `h${level()}` as const;
    const tagName = extractTagName(ref.get);
    const isNativeHeading = createMemo(
      () => !!tagName() && /^h\d$/.test(tagName()!),
    );

    props = mergeProps(
      {
        render: Element(),
        get role() {
          return !isNativeHeading() ? "heading" : undefined;
        },
        get "aria-level"() {
          return !isNativeHeading() ? level() : undefined;
        },
        ref: ref.set,
      },
      props,
    );

    return props;
  },
);

/**
 * Renders a heading element. The element type (or the `aria-level` attribute,
 * if the element type is not a native heading) is determined by the context
 * level provided by the closest
 * [`HeadingLevel`](https://solid.ariakit.com/reference/heading-level) ancestor.
 * @see https://solid.ariakit.com/components/heading
 * @example
 * ```jsx
 * <HeadingLevel>
 *   <Heading>Heading 1</Heading>
 *   <HeadingLevel>
 *     <Heading>Heading 2</Heading>
 *   </HeadingLevel>
 * </HeadingLevel>
 * ```
 */
export const Heading = function Heading(props: HeadingProps) {
  const htmlProps = useHeading(props);
  return createInstance(TagName, htmlProps);
};

export interface HeadingOptions<
  _T extends ValidComponent = TagName,
> extends Options {}

export type HeadingProps<T extends ValidComponent = TagName> = Props<
  T,
  HeadingOptions<T>
>;

// packages/ariakit-react-core/src/heading/heading.tsx
import { useMergeRefs, useTagName } from "@ariakit/react-utils";
import { createElement, createHook, forwardRef } from "@ariakit/react-utils";
import type { Options } from "@ariakit/react-utils";
import type { Props } from "@ariakit/react-utils";
import type { ElementType } from "react";
import { useContext, useMemo, useRef } from "react";
import { HeadingContext } from "./heading-context.tsx";
import type { HeadingLevels } from "./utils.ts";

type HeadingElements = `h${HeadingLevels}`;
const TagName = "h1" satisfies ElementType;
type TagName = HeadingElements;
type HTMLType = HTMLElementTagNameMap[TagName];

/**
 * Returns props to create a `Heading` component. The element type (or the
 * `aria-level` prop, if the element type is not a native heading) is determined
 * by the context level provided by the parent `HeadingLevel` component.
 * @see https://ariakit.com/components/heading
 * @example
 * ```jsx
 * const props = useHeading();
 * <Role {...props}>Heading</Role>
 * ```
 */
export const useHeading = createHook<TagName, HeadingOptions>(
  function useHeading(props) {
    const ref = useRef<HTMLType>(null);
    const level: HeadingLevels = useContext(HeadingContext) || 1;
    const Element = `h${level}` as const;
    const tagName = useTagName(ref, Element);
    const isNativeHeading = useMemo(
      () => !!tagName && /^h\d$/.test(tagName),
      [tagName],
    );

    props = {
      render: <Element />,
      role: !isNativeHeading ? "heading" : undefined,
      "aria-level": !isNativeHeading ? level : undefined,
      ...props,
      ref: useMergeRefs(ref, props.ref),
    };

    return props;
  },
);

/**
 * Renders a heading element. The element type (or the `aria-level` attribute,
 * if the element type is not a native heading) is determined by the context
 * level provided by the closest
 * [`HeadingLevel`](https://ariakit.com/reference/heading-level) ancestor.
 * @see https://ariakit.com/components/heading
 * @example
 * ```jsx
 * <HeadingLevel>
 *   <Heading>Heading 1</Heading>
 *   <HeadingLevel>
 *     <Heading>Heading 2</Heading>
 *   </HeadingLevel>
 * </HeadingLevel>
 * ```
 */
export const Heading = forwardRef(function Heading(props: HeadingProps) {
  const htmlProps = useHeading(props);
  return createElement(TagName, htmlProps);
});

export interface HeadingOptions<
  _T extends ElementType = TagName,
> extends Options {}

export type HeadingProps<T extends ElementType = TagName> = Props<
  T,
  HeadingOptions<T>
>;
