// packages/ariakit-react-core/src/utils/types.ts
import type * as React from "react";
import type { AnyObject, EmptyObject } from "@ariakit/core/utils/types";

/**
 * Render prop type.
 * @template P Props
 * @example
 * const children: RenderProp = (props) => <div {...props} />;
 */
export type RenderProp<
  P = React.HTMLAttributes<any> & React.RefAttributes<any>,
> = (props: P) => React.ReactNode;

/**
 * The `as` prop.
 * @template P Props
 */
export type As<P = any> = React.ElementType<P>;

/**
 * The `wrapElement` prop.
 */
export type WrapElement = (element: React.ReactElement) => React.ReactElement;

/**
 * Props with the `as` prop.
 * @template T The `as` prop
 * @example
 * type ButtonOptions = Options<"button">;
 */
export type Options<T extends As = any> = {
  /**
   * @deprecated
   * Use the [`render`](https://ariakit.org/guide/composition) prop instead.
   */
  as?: T;
};

/**
 * Props that automatically includes HTML props based on the `as` prop.
 * @template O Options
 * @example
 * type ButtonHTMLProps = HTMLProps<Options<"button">>;
 */
export type HTMLProps<O extends Options> = {
  wrapElement?: WrapElement;
  render?: RenderProp | React.ReactElement;
  [index: `data-${string}`]: unknown;
} & Omit<React.ComponentPropsWithRef<NonNullable<O["as"]>>, keyof O>;

/**
 * Options & HTMLProps
 * @template O Options
 * @example
 * type ButtonProps = Props<Options<"button">>;
 */
export type Props<O extends Options> = O & HTMLProps<O>;

export type Options2 = {
  wrapElement?: WrapElement;
  render?: RenderProp | React.ReactElement;
};

export type HTMLProps2<
  T extends React.ElementType,
  P extends AnyObject = EmptyObject,
> = Omit<React.ComponentPropsWithRef<T>, keyof P> & {
  [index: `data-${string}`]: unknown;
};

export type Props2<
  T extends React.ElementType,
  P extends AnyObject = EmptyObject,
> = P & HTMLProps2<T, P>;

export interface Hook2<
  T extends React.ElementType,
  O extends AnyObject = EmptyObject,
> {
  <ElementType extends React.ElementType = T>(
    props?: Props2<ElementType, O>,
  ): HTMLProps2<ElementType, O>;
}

/**
 * A component that supports the `as` prop and the `children` prop as a
 * function.
 * @template O Options
 * @example
 * type ButtonComponent = Component<Options<"button">>;
 */
export interface Component<O extends Options> {
  <T extends As>(
    props: Props<{ as: T } & Omit<O, "as">>,
  ): React.ReactElement | null;
  (props: Props<O>): React.ReactElement | null;
  displayName?: string;
}

/**
 * A component hook that supports the `as` prop and the `children` prop as a
 * function.
 * @template O Options
 * @example
 * type ButtonHook = Hook<Options<"button">>;
 */
export interface Hook<O extends Options> {
  <T extends As = NonNullable<O["as"]>>(
    props?: Props<Options<T> & Omit<O, "as">>,
  ): HTMLProps<Options<T>>;
  displayName?: string;
}

// packages/ariakit-solid-core/src/utils/types.ts
import type { AnyObject, EmptyObject } from "@ariakit/core/utils/types";
import type { ComponentProps, JSX, ValidComponent } from "solid-js";

/**
 * The `wrapElement` prop.
 */
export type WrapElement = Array<JSX.Element>;

/**
 * Custom props including the `render` prop.
 */
export interface Options {
  wrapElement?: WrapElement;
  /**
   * Allows the component to be rendered as a different HTML element or Solid
   * component. The value can be an `As` component instance or a function that
   * takes in the original component props and gives back a Solid component
   * instance with the props merged.
   *
   * Check out the [Composition](https://solid.ariakit.org/guide/composition) guide
   * for more details.
   */
  render?: JSX.Element; // TODO: function support
}

/**
 * HTML props based on the element type, excluding custom props.
 * @template T The element type.
 * @template P Custom props.
 * @example
 * type ButtonHTMLProps = HTMLProps<"button", { custom?: boolean }>;
 */
export type HTMLProps<
  T extends ValidComponent,
  P extends AnyObject = EmptyObject,
> = Omit<ComponentProps<T>, keyof P> & {
  [index: `data-${string}`]: unknown;
};

/**
 * Props based on the element type, including custom props.
 * @template T The element type.
 * @template P Custom props.
 */
export type Props<
  T extends ValidComponent,
  P extends AnyObject = EmptyObject,
> = P & HTMLProps<T, P>;

/**
 * A component hook that supports the `render` prop and returns HTML props based
 * on the element type.
 * @template T The element type.
 * @template P Custom props.
 * @example
 * type UseButton = Hook<"button", { custom?: boolean }>;
 */
export type Hook<
  T extends ValidComponent,
  P extends AnyObject = EmptyObject,
> = <ElementType extends ValidComponent = T>(
  props?: Props<ElementType, P>,
) => HTMLProps<ElementType, P>;
